# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1eb28b3ecca8c89453d8dcd157643500d7a6cf46a74ef0679345fc9616312cfae4196a1ec69da488c904661c9fb636e53f3a969ebba31e6009e4ea77483a83d6

test:
  secret_key_base: bef6d0d9b9e6150f94788957a7072f2f08f347fbcaefa774c401c8a90ae38f38415a6bf62e298084c3c06598378a46544e18bbee6dbbf88070d5735b998cad75

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
